data:
  train_files: Coobiw/IE-Bench-4k@train
  val_files: Coobiw/IE-Bench-4k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 4096
  max_response_length: 4096
  rollout_batch_size: 64
  val_batch_size: 128
  format_prompt: ./examples/format_prompt/ie_critic_r1.jinja
  shuffle: true
  seed: 42
  max_pixels: 1048576 # 1024 x 1024
  min_pixels: 262144 # 512 x 512
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 0 #1.0e-2
  keep_pos_ratio: 1.0
  keep_neg_ratio: 1.0
  compute_new_adv: false

worker:
  actor:
    global_batch_size: 64
    micro_batch_size_per_device_for_update: 8 # 4
    micro_batch_size_per_device_for_experience: 64 # 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    clip_ratio_dual: 3.0
    entropy_coeff: 0.
    loss_agg_mode: "token-mean"
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: false  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8
    temperature: 1.0
    top_p: 1.0
    gpu_memory_utilization: 0.6 # 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 2
    force_think_template: true  # Use the think chat template and prepend <think> before the response
    val_override_config:
      temperature: 1.0
      n: 1
      top_p: 0.9

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: function
    score_function: ./examples/score_function/ie_ciritc_r1.py:compute_score_l1
    score_function_kwargs:
      format_weight: 1.0
      r_min: 0.05
      diff_at_rmin: 1.0
      use_floor: true
      strict_format: false

trainer:
  total_episodes: 5
  # logger: ["console", "wandb"]
  logger: ["console"]
  project_name: ie_critic_r1-rl-exp
  experiment_name: ie_critic_r1
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: 1  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 20
  save_freq: -1 # -1 to disable
  save_limit: 20  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null
  train_generations_to_log: 10     # üÜï Training logging (ÊØèÊ¨° 10 ‰∏™Ê†∑Êú¨)
  train_log_freq: 10              # üÜï ÊØè 1 Ê≠• log ‰∏ÄÊ¨°